name: Build Project
on:
  pull_request:
    branches:
      - dev
      - main
jobs:
  deploy:
    name: Build
    runs-on: macOS-latest
    timeout-minutes: 25
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEB_HOOK_PR }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Notify Slack - Success
        uses: act10ns/slack@v1
        with:
          status: In Progress
          channel: 'bc-vaccine-card-ios'
          message: There is a new PR! Building...
#     - name: Notify Slack - start
#       uses: rtCamp/action-slack-notify@v2.2.0
#       env:
#         SLACK_WEBHOOK: ${{ secrets.SLACK_WEB_HOOK_PR }}
#         SLACK_CHANNEL: bc-vaccine-card-ios
#         SLACK_USERNAME: "My Health iOS Bot"
#         SLACK_TITLE: "There is a new PR!"
#         SLACK_LINK_NAMES: true
#         SLACK_MESSAGE: "building..."
        
      - name: Install gpg
        run: brew install gnupg
        
      - name: Setup profiles and certs
        env:
          IOS_KEYS: ${{ secrets.IOS_KEYS }}
          FIREBASE_PROVISIONING: ${{ secrets.FIREBASE_PROVISIONING }}
        run: ./.github/secrets/decrypt_secrets.sh
        
      - name: Build Dev target
        env:
          PR_NUMBER: $(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        run: ./.github/scripts/build.sh
        
      - name: Build Prod target
        env:
          PR_NUMBER: $(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        run: ./.github/scripts/build_prod.sh
        
      - name: Notify Slack - Success
        uses: act10ns/slack@v1
        with:
          status: Completed
          channel: 'bc-vaccine-card-ios'
          message: PR did build successfully