name: Build Project
on:
  pull_request:
    branches:
      - dev
env:
  DEVELOPER_DIR: /Applications/Xcode_13.1.app/Contents/Developer
jobs:
  deploy:
    name: Build
    runs-on: macOS-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install gpg
        run: brew install gnupg
      - name: Setup provisioning profile
        env:
          IOS_KEYS: ${{ secrets.IOS_KEYS }}
          FIREBASE_PROVISIONING: ${{ secrets.FIREBASE_PROVISIONING }}
        run: ./.github/secrets/decrypt_secrets.sh
      - name: Building project
        env:
          PR_NUMBER: $(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        run: ./.github/scripts/build.sh